#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                  

# Global Configs
[config]
version_check = true

# Templates

# Spicetify
#[templates.spicetify]
#input_path = '~/.config/matugen/templates/spotify-colors.ini'
#output_path = '~/.config/spicetify/Themes/Comfy/color.ini'
#post_hook = '~/.spicetify/spicetify apply'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

# Rofi
[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/matugen/rofi-colors.rasi'

# Hyprland
[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/matugen/hyprland-colors.conf'

# Hyprlock
#[templates.hyprlock]
#input_path = '~/.config/matugen/templates/matugen-hyprlock.conf'
#output_path = '~/.config/hypr/hyprlock/matugen/matugen-hyprlock.conf'

# Waybar
[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.cache/wallust/waybar.css'
# post_hook = 'pkill -SIGUSR2 waybar'

# Swaync
#[templates.swaync]
#input_path = '~/.config/matugen/templates/matugen-swaync.css'
#output_path = '~/.config/swaync/matugen/matugen-swaync.css'
#post_hook = 'swaync-client -rs'


# Gtk3
#[templates.gtk3]
#input_path = '~/.config/matugen/templates/matugen-gtk.css'
#output_path = '~/.config/gtk-3.0/gtk.css'

# GTk4
#[templates.gtk4]
#input_path = '~/.config/matugen/templates/matugen-gtk.css'
#output_path = '~/.config/gtk-4.0/gtk.css'

# Qt5
#[templates.qt5]
#input_path = '~/.config/matugen/templates/qtct-colors.conf'
#output_path = '~/.config/qt5ct/colors/matugen-qt5ct.conf'

# Qt6
#[templates.qt6]
#input_path = '~/.config/matugen/templates/qtct-colors.conf'
#output_path = '~/.config/qt6ct/colors/matugen-qt6ct.conf'

# Cava
#[templates.cava]
#input_path = '~/.config/matugen/templates/matugen-cava'
#output_path = '~/.config/cava/config'

# Neovim
#[templates.neovim]
#input_path = '~/.config/matugen/templates/matugen-colors.vim'
#output_path = '~/.cache/wal/colors-wal.vim'

# Pywalfox
[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

# Librewolf startup page
#[templates.librewolf]
#input_path = '~/.config/matugen/templates/matugen-librewolf-startup-page.css'
#output_path = '~/.local/share/startup-page/app.css'

# Walogram
[templates.walogram]
input_path = '~/.config/matugen/templates/colors.sh'
output_path = '~/.cache/wal/colors.sh'
post_hook = 'walogram'